version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_HASH=${API_HASH}
      - API_ID=${API_ID}
      - STRING_SESSION=${STRING_SESSION}
      - PASSWORD = ${PASSWORD}
      - SUDO_USERS = ${SUDO_USERS}
